# Generated by Django 5.2.4 on 2025-07-13 12:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='videokeyword',
            name='keyword',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.keyword'),
        ),
        migrations.AddField(
            model_name='videokeyword',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.video'),
        ),
        migrations.AddField(
            model_name='video',
            name='keywords',
            field=models.ManyToManyField(related_name='videos', through='media.VideoKeyword', to='media.keyword'),
        ),
        migrations.AlterUniqueTogether(
            name='videokeyword',
            unique_together={('video', 'keyword')},
        ),
    ]
